sudo: false
language: python
python:
- "2.7"
- "3.5"
install:
- pip install -U pytest
- pip install -U coveralls
script:
- python setup.py develop
- coverage run --append --source=pytest_stash.py -m pytest ./_tests/
after_success:
- coveralls
